import { Asset } from './types';

export const allAssets: Asset[] = [
  // INDIAN STOCKS
  {
    ticker: 'RELIANCE', name: 'Reliance Industries', seg: 'IN', cat: 'Energy/Retail/Telecom',
    inv: 68810, curr: 70240, ret: 2.08,
    scores: { quality: 6, growth: 5, moat: 9, mgmt: 7, valuation: 6, safety: 7 },
    verdict: 'HOLD', vclass: 'v-hold',
    pe: 26, roe: 8.8, cagr5: 10, debt: 'High', promoter: '50.3%', mktCap: '₹19.07L Cr',
    news: 'Jio 5G monetisation accelerating; new energy capex cycle near peak. SEBI cleared RIL-Disney merger creating India\'s largest media company. Green energy bets could rerate 2027+.',
    bull: 'Jio+Retail monetisation. Green energy optionality. New media giant post Disney merger.',
    bear: 'Low ROE 8.8%. High debt. CapEx compresses FCF through 2026.',
    tags: ['Green Energy Pivot', 'Jio 5G', 'Disney Merger', '₹19L Cr Mktcap'],
    risks: { geopolitical: 3, regulatory: 5, competition: 5, valuation: 5, execution: 6 },
    trend: [65, 66, 68, 67, 69, 70, 70.2]
  },
  {
    ticker: 'AIRTEL', name: 'Bharti Airtel', seg: 'IN', cat: 'Telecom',
    inv: 26820, curr: 28062, ret: 4.63,
    scores: { quality: 7, growth: 7, moat: 8, mgmt: 8, valuation: 5, safety: 6 },
    verdict: 'BUY', vclass: 'v-buy',
    pe: 62, roe: 18, cagr5: 14, debt: 'High', promoter: '56.2%', mktCap: '₹11.28L Cr',
    news: 'Airtel Q3 FY26 ARPU hit ₹245 — highest ever. Africa revenue growing 18% YoY in constant currency. Another tariff hike expected mid-2026 which will flow directly to EBITDA.',
    bull: 'Telecom duopoly. Each ₹10 ARPU hike = ₹7,200 Cr annual revenue. Africa optionality underpriced.',
    bear: 'High debt. 62x PE expensive. Jio competition relentless.',
    tags: ['ARPU ₹245 Record', 'Africa 18% Growth', 'Tariff Hike Coming', 'Duopoly'],
    risks: { geopolitical: 2, regulatory: 6, competition: 7, valuation: 6, execution: 3 },
    trend: [25, 26, 25.5, 27, 27.8, 28, 28.1]
  },
  {
    ticker: 'MCX', name: 'MCX (Multi Commodity Exchange)', seg: 'IN', cat: 'Exchange',
    inv: 64556, curr: 92232, ret: 42.87,
    scores: { quality: 8, growth: 7, moat: 10, mgmt: 6, valuation: 5, safety: 8 },
    verdict: 'HOLD — BOOK PARTIAL', vclass: 'v-hold',
    pe: 55, roe: 22, cagr5: 12, debt: 'Zero', promoter: '0%', mktCap: '₹13,400 Cr',
    news: 'MCX volume surged 34% YoY in Feb 2026 driven by crude oil and gold volatility. Tech migration now fully stable. SEBI approved new electricity derivatives — could be next growth driver.',
    bull: 'Only commodity exchange in India. Zero debt. Volume growth 34% YoY. Electricity derivatives new TAM.',
    bear: 'No promoter holding — governance risk. PE 55x expensive after 43% run. Competition from BSE Commodity.',
    tags: ['Regulatory Monopoly', 'Volume +34% YoY', 'Electricity Derivatives', 'Book Some Profits'],
    risks: { geopolitical: 1, regulatory: 5, competition: 3, valuation: 7, execution: 4 },
    trend: [70, 75, 72, 80, 85, 90, 92.2]
  },
  {
    ticker: 'SUNPHARMA', name: 'Sun Pharmaceutical', seg: 'IN', cat: 'Pharma',
    inv: 15900, curr: 17994, ret: 13.17,
    scores: { quality: 7, growth: 6, moat: 7, mgmt: 7, valuation: 6, safety: 7 },
    verdict: 'HOLD', vclass: 'v-hold',
    pe: 35, roe: 15, cagr5: 9.9, debt: 'Low', promoter: '54.5%', mktCap: '₹4.27L Cr',
    news: 'ILUMYA US prescriptions growing 22% YoY. Sun Pharma gaining specialty market share in dermatology. India domestic formulations growing 12%. FDA inspections cleared at Halol facility.',
    bull: 'US specialty shift (ILUMYA, Winlevi) — margin accretive. India formulations stable.',
    bear: '9.9% revenue CAGR low for a pharma. Generic price erosion in US.',
    tags: ['ILUMYA +22% US', 'FDA Halol Cleared', 'Specialty Shift', 'India +12%'],
    risks: { geopolitical: 3, regulatory: 7, competition: 5, valuation: 5, execution: 4 },
    trend: [16, 16.5, 17, 16.8, 17.5, 17.8, 18]
  },
  {
    ticker: 'TITAN', name: 'Titan Company', seg: 'IN', cat: 'Consumer/Jewellery',
    inv: 49993, curr: 63669, ret: 27.35,
    scores: { quality: 9, growth: 8, moat: 9, mgmt: 9, valuation: 4, safety: 8 },
    verdict: 'BUY ON DIPS', vclass: 'v-buy',
    pe: 80, roe: 36, cagr5: 22, debt: 'Zero', promoter: '52.9%', mktCap: '₹3.76L Cr',
    news: 'Tanishq added 42 new stores in H2 FY26. Wedding season demand driving Q4 jewellery growth. EyePlus opticals now 1,000+ stores. Gold price rally boosting Tanishq ASP and margins.',
    bull: '22% 5Y CAGR. Zero debt. Tata backed. Tanishq brand moat irreplaceable. +42 new stores.',
    bear: '80x PE — very expensive. Any slowdown in premium consumption hits hard.',
    tags: ['Tanishq +42 Stores', 'Gold Price Tailwind', 'EyePlus 1000+ Stores', 'Premium Consumption'],
    risks: { geopolitical: 1, regulatory: 2, competition: 4, valuation: 9, execution: 3 },
    trend: [55, 58, 60, 59, 62, 63, 63.6]
  },
  {
    ticker: 'TCS', name: 'Tata Consultancy Services', seg: 'IN', cat: 'IT Services',
    inv: 30940, curr: 25576, ret: -17.33,
    scores: { quality: 9, growth: 5, moat: 8, mgmt: 9, valuation: 7, safety: 9 },
    verdict: 'STRONG BUY', vclass: 'v-strong',
    pe: 24, roe: 48, cagr5: 12, debt: 'Zero', promoter: '72.4%', mktCap: '₹9.25L Cr',
    news: 'TCS Q3 FY26 deal wins $10.2B — best in 6 quarters. AI transformation programmes driving large deal pipeline. Trading at 3-year P/E low of 24x. Management committed to 26-28% margins.',
    bull: '$10.2B deal wins. ROE 48%. Zero debt. 72% promoter. AI transformation demand inflecting. P/E 24x — cheapest in years.',
    bear: 'Down 17% from buy. AI replacing junior dev roles = near-term revenue risk. Rupee appreciation headwind.',
    tags: ['$10.2B Deal Wins', 'ROE 48%', 'PE 24x 3-Year Low', 'AI Demand Inflecting'],
    risks: { geopolitical: 2, regulatory: 3, competition: 7, valuation: 3, execution: 4 },
    trend: [30, 29, 28, 27, 26, 25.8, 25.5]
  },
  {
    ticker: 'BAJAJ AUTO', name: 'Bajaj Auto', seg: 'IN', cat: 'Auto (2W/3W)',
    inv: 35080, curr: 39264, ret: 11.93,
    scores: { quality: 8, growth: 7, moat: 8, mgmt: 8, valuation: 6, safety: 8 },
    verdict: 'HOLD', vclass: 'v-hold',
    pe: 32, roe: 28, cagr5: 14, debt: 'Zero', promoter: '55%', mktCap: '₹2.74L Cr',
    news: 'Bajaj 3W exports hit record highs in Q3 FY26. Chetak EV sales up 78% YoY crossing 1L units cumulative. KTM partnership driving premium 2W growth. Africa market opening up for exports.',
    bull: 'World\'s largest 3W exporter. Chetak EV gaining ground. KTM alliance adds premium segment.',
    bear: 'EV transition risk in domestic 2W. Competition from Ola, TVS, Hero intensifying.',
    tags: ['Chetak EV +78% YoY', '3W Export Record', 'KTM Premium Play', 'Africa Exports'],
    risks: { geopolitical: 4, regulatory: 3, competition: 6, valuation: 5, execution: 4 },
    trend: [36, 37, 38, 37.5, 39, 39.2, 39.3]
  },
  {
    ticker: 'JIOFIN', name: 'Jio Financial Services', seg: 'IN', cat: 'Fintech/NBFC',
    inv: 65598, curr: 71456, ret: 8.93,
    scores: { quality: 4, growth: 6, moat: 6, mgmt: 7, valuation: 3, safety: 5 },
    verdict: 'SPECULATIVE HOLD', vclass: 'v-spec',
    pe: 95, roe: 0.87, cagr5: 0, debt: 'Low', promoter: '47.1%', mktCap: '₹1.56L Cr',
    news: 'Jio Financial launched JioFinance app to 10M users. Insurance JV with Munich Re approved. AMC licence received from SEBI. Blackrock JV AUM reached ₹2,100 Cr.',
    bull: 'Reliance backing. AMC + insurance + lending + payments = full financial services stack. Blackrock JV AUM growing.',
    bear: 'ROE 0.87%. PE 95x for near-zero earnings. Very early stage. Execution unproven.',
    tags: ['JioFinance 10M Users', 'Munich Re JV', 'AMC Licence Received', 'Blackrock JV ₹2100 Cr'],
    risks: { geopolitical: 2, regulatory: 5, competition: 7, valuation: 9, execution: 8 },
    trend: [68, 69, 70, 69.5, 71, 71.2, 71.4]
  },
  {
    ticker: 'INFY', name: 'Infosys', seg: 'IN', cat: 'IT Services',
    inv: 30536, curr: 24860, ret: -18.59,
    scores: { quality: 8, growth: 5, moat: 7, mgmt: 7, valuation: 7, safety: 8 },
    verdict: 'STRONG BUY', vclass: 'v-strong',
    pe: 23, roe: 30.7, cagr5: 11, debt: 'Zero', promoter: '14.8%', mktCap: '₹5.29L Cr',
    news: 'Infosys FY26 revenue guidance raised to 8.5–10.5% in CC. Large deal signings $4.5B in Q3. Topaz AI platform signed 70+ Fortune 500 clients. Dividend yield at 3.5% — highest in 5 years.',
    bull: 'ROE 30.7%. 3.5% dividend yield. Topaz AI 70+ Fortune 500 clients. Guidance raised.',
    bear: 'Down 18.6% from buy. Low promoter holding 14.8%. Management attrition elevated.',
    tags: ['Guidance Raised 8.5-10.5%', 'Topaz AI 70+ Clients', '3.5% Dividend Yield', '$4.5B Large Deals'],
    risks: { geopolitical: 2, regulatory: 3, competition: 7, valuation: 3, execution: 5 },
    trend: [28, 27, 26.5, 26, 25.5, 25, 24.8]
  },
  {
    ticker: 'BAJAJFIN', name: 'Bajaj Finance', seg: 'IN', cat: 'NBFC/Lending',
    inv: 90745, curr: 109273, ret: 20.42,
    scores: { quality: 9, growth: 8, moat: 8, mgmt: 9, valuation: 7, safety: 7 },
    verdict: 'STRONG BUY', vclass: 'v-strong',
    pe: 28, roe: 22, cagr5: 25, debt: 'High (nature)', promoter: '55.9%', mktCap: '₹5.90L Cr',
    news: 'Bajaj Finance Q3 FY26 AUM crossed ₹4L Cr milestone. EMI card base 45M+ — fastest growing. NPA at 0.27% — pristine. Kotak target ₹1,200 with 26% upside. New ₹2L Cr AUM target by FY28.',
    bull: 'AUM ₹4L Cr. EMI card 45M+. NPA 0.27%. 25% CAGR consistency. Rajeev Jain execution.',
    bear: 'High PE 28x for a NBFC. Credit cycle risk if macro deteriorates. Competition from fintech.',
    tags: ['AUM ₹4L Cr Milestone', 'EMI Card 45M+', 'NPA 0.27%', '₹2L Cr AUM Target FY28'],
    risks: { geopolitical: 1, regulatory: 5, competition: 5, valuation: 4, execution: 2 },
    trend: [95, 98, 102, 105, 107, 108, 109.2]
  },
  {
    ticker: 'ADANIENT', name: 'Adani Enterprises', seg: 'IN', cat: 'Infrastructure/Diversified',
    inv: 57431, curr: 48958, ret: -14.76,
    scores: { quality: 4, growth: 8, moat: 6, mgmt: 5, valuation: 3, safety: 3 },
    verdict: 'EXIT / REDUCE', vclass: 'v-exit',
    pe: 95, roe: 9.5, cagr5: 30, debt: 'Very High', promoter: '72.6%', mktCap: '₹2.31L Cr',
    news: 'US DOJ dropped bribery charges in Feb 2026 — positive. But debt-to-equity remains above 3x. Airport revenue growing. Solar manufacturing achieving scale. Stock recovering from 52-week low.',
    bull: 'DOJ charges dropped. Airport + solar + roads scaling. Revenue CAGR 30%.',
    bear: 'Debt-to-equity 3x+. Governance concerns linger. Low ROE 9.5%. You\'re -14.76%.',
    tags: ['DOJ Charges Dropped Feb 2026', 'Still -14.76%', 'Debt/Equity 3x+', 'Consider Exiting'],
    risks: { geopolitical: 4, regulatory: 8, competition: 4, valuation: 8, execution: 7 },
    trend: [55, 52, 48, 45, 47, 48, 48.9]
  },
  {
    ticker: 'ASIANPAINT', name: 'Asian Paints', seg: 'IN', cat: 'Consumer/Paints',
    inv: 23164, curr: 23164, ret: 0,
    scores: { quality: 8, growth: 5, moat: 7, mgmt: 8, valuation: 5, safety: 8 },
    verdict: 'HOLD', vclass: 'v-hold',
    pe: 55, roe: 26.5, cagr5: 11.4, debt: 'Zero', promoter: '52.8%', mktCap: '₹2.13L Cr',
    news: 'Birla Opus now present in 20,000+ dealer networks directly competing. Asian Paints volume growth slowed to 4% vs 12% two years ago. The premium Royale segment still holding well. Margin recovery expected in Q1 FY27.',
    bull: 'Zero debt. ROE 26.5%. Premium brand resilient. Margin recovery underway.',
    bear: 'Birla Opus eating market share. Volume growth from 12% → 4%. PE still elevated at 55x.',
    tags: ['Birla Opus Competition', 'Volume Growth Slowing', 'Premium Brand Resilient', 'Margin Recovery Q1FY27'],
    risks: { geopolitical: 1, regulatory: 2, competition: 8, valuation: 6, execution: 5 },
    trend: [24, 23.5, 23, 23.2, 23.1, 23, 23.1]
  },
  {
    ticker: 'INDIGO', name: 'IndiGo (InterGlobe Aviation)', seg: 'IN', cat: 'Aviation',
    inv: 129053, curr: 104395, ret: -19.11,
    scores: { quality: 5, growth: 6, moat: 7, mgmt: 4, valuation: 5, safety: 4 },
    verdict: 'REDUCE', vclass: 'v-reduce',
    pe: 52, roe: 77, cagr5: 15, debt: 'High', promoter: '41.6%', mktCap: '₹1.66L Cr',
    news: 'CEO Pieter Elbers resigned March 10 2026 — major leadership risk. IndiGo imposed ₹2,500 fuel surcharge per ticket. ATF prices up 28% YoY due to West Asia conflict. Still holds 62% domestic market share.',
    bull: '62% domestic market share. Air traffic growing 15% PA. Duopoly (IndiGo + Air India).',
    bear: 'CEO resigned. ATF up 28%. Down 19% from your buy. Aviation = cyclical, capital-intensive.',
    tags: ['CEO Resigned March 2026', 'ATF +28% YoY', '62% Market Share', 'Fuel Surcharge ₹2500'],
    risks: { geopolitical: 7, regulatory: 4, competition: 5, valuation: 5, execution: 8 },
    trend: [120, 115, 110, 112, 108, 105, 104.3]
  },
  {
    ticker: 'MOTHERSON', name: 'Motherson Sumi (Samvardhana)', seg: 'IN', cat: 'Auto Ancillary',
    inv: 20222, curr: 24729, ret: 22.29,
    scores: { quality: 6, growth: 7, moat: 6, mgmt: 6, valuation: 6, safety: 6 },
    verdict: 'HOLD', vclass: 'v-hold',
    pe: 35, roe: 10.6, cagr5: 16, debt: 'Moderate', promoter: '21.4%', mktCap: '₹1.24L Cr',
    news: 'Motherson Q3 FY26 revenue ₹27,100 Cr +12% YoY. 5 new EV wiring harness contracts won from BMW and Mercedes. Germany facility running at 85% utilisation. Promoter stake reduced from 24% to 21.4%.',
    bull: 'EV wiring harness contracts — BMW, Mercedes. Revenue growth 12% YoY. Global 30+ countries.',
    bear: 'Promoter stake declining. ROE 10.6% modest. Thin margins. Auto cycle risk.',
    tags: ['BMW+Mercedes EV Contracts', '5 New EV Wins', 'Germany 85% Utilisation', 'Promoter Stake ↓'],
    risks: { geopolitical: 5, regulatory: 2, competition: 5, valuation: 5, execution: 5 },
    trend: [21, 22, 23, 22.5, 24, 24.5, 24.7]
  },
  {
    ticker: 'BAJAJFINSV', name: 'Bajaj Finserv', seg: 'IN', cat: 'Diversified Financials',
    inv: 90106, curr: 93445, ret: 3.71,
    scores: { quality: 7, growth: 7, moat: 7, mgmt: 8, valuation: 6, safety: 7 },
    verdict: 'HOLD', vclass: 'v-hold',
    pe: 29, roe: 14, cagr5: 18, debt: 'Low', promoter: '60.7%', mktCap: '₹2.98L Cr',
    news: 'Allianz formally exited JV — Bajaj Allianz now 100% owned. This removes long-term uncertainty. Insurance business growing premiums 19% YoY. Bajaj Finance subsidiary continues to compound. New health insurance product gaining traction.',
    bull: 'Allianz exit removes JV complexity. Insurance 19% premium growth. Bajaj Finance subsidiary compounding.',
    bear: 'Holding company discount 30-40% persistent. 29x PE modest for a holding company. ROE 14% diluted.',
    tags: ['Allianz Exited — Now 100% Owned', 'Insurance +19% Premiums', 'Bajaj Finance Subsidiary', 'Health Insurance New Product'],
    risks: { geopolitical: 1, regulatory: 5, competition: 5, valuation: 5, execution: 3 },
    trend: [90, 91, 92, 91.5, 93, 93.2, 93.4]
  },
  {
    ticker: 'ETERNAL', name: 'Eternal (Zomato)', seg: 'IN', cat: 'QCommerce/Foodtech',
    inv: 33729, curr: 33729, ret: 0,
    scores: { quality: 5, growth: 9, moat: 7, mgmt: 6, valuation: 3, safety: 5 },
    verdict: 'HOLD — SPECULATIVE', vclass: 'v-spec',
    pe: 280, roe: 3, cagr5: 60, debt: 'Zero', promoter: '4.7%', mktCap: '₹2.45L Cr',
    news: 'Blinkit crossed 1,000 dark stores in India — first QCommerce player to do so. Albinder Dhindsa named new CEO (Deepinder stepping back). Q3 FY26 revenue +63% YoY. Hyperpure B2B food-tech gaining scale.',
    bull: 'Blinkit 1,000 dark stores — massive moat. Revenue +63% YoY. Hyperpure B2B scaling. Zero debt.',
    bear: 'PE 280x absurd on trailing basis. CEO transition risk. QCommerce competition from Swiggy Instamart, Zepto.',
    tags: ['Blinkit 1000 Dark Stores', 'Revenue +63% YoY', 'New CEO Albinder', 'Hyperpure B2B Scaling'],
    risks: { geopolitical: 1, regulatory: 4, competition: 8, valuation: 9, execution: 6 },
    trend: [30, 31, 32, 31.5, 33, 33.5, 33.7]
  },
  {
    ticker: 'HDFC BANK', name: 'HDFC Bank', seg: 'IN', cat: 'Private Banking',
    inv: 47422, curr: 42853, ret: -9.64,
    scores: { quality: 8, growth: 6, moat: 9, mgmt: 8, valuation: 8, safety: 9 },
    verdict: 'STRONG BUY', vclass: 'v-strong',
    pe: 19, roe: 16, cagr5: 18, debt: 'By nature', promoter: '0%', mktCap: '₹13.19L Cr',
    news: 'HDFC Bank Q3 FY26 loan growth 14.5% YoY with CASA ratio improving to 38%. NIM stabilising at 3.4% post-merger. Sashidhar Jagdishan guided deposit franchise growing ahead of credit. PE at 19x — cheapest in 7 years.',
    bull: 'PE 19x — 7-year low. Loan growth 14.5%. NIM stabilising. Merger digestion 80% done. Best asset quality in sector.',
    bear: 'Down 9.6%. Post-merger CASA dilution. Slower credit growth vs pre-merger. ROE compressed at 16% vs 18% pre-merger.',
    tags: ['PE 19x 7-Year Low', 'NIM Stabilising 3.4%', 'Loan Growth 14.5%', 'CASA 38%'],
    risks: { geopolitical: 1, regulatory: 5, competition: 4, valuation: 2, execution: 3 },
    trend: [48, 47, 46, 45, 44, 43.5, 42.8]
  },
  // US STOCKS
  {
    ticker: 'GOOGL', name: 'Alphabet Inc.', seg: 'US', cat: 'Tech / AI Cloud / Advertising',
    inv: 900.68, curr: 1196.08, ret: 32.78,
    scores: { quality: 9, growth: 8, moat: 10, mgmt: 9, valuation: 8, safety: 8 },
    verdict: 'STRONG BUY', vclass: 'v-strong',
    pe: 28.5, roe: 35.7, cagr5: 15, debt: '0.16x D/E', promoter: 'Insiders 11%', mktCap: '$2.05T',
    news: 'Q4 2025: Revenue $113.8B +18%. Google Cloud grew 48% to $17.7B. Gemini at 750M MAU. $70B buyback authorised. Waymo 400K rides/week — approaching commercialisation. Wiz $32B acquisition closing mid-2026.',
    bull: '$240B cloud backlog. Waymo commercial scale. $130B cash. 90% search share unchanged vs AI.',
    bear: '$175B CapEx compresses EPS +6% in 2026. DOJ antitrust potential Chrome/Android divestiture.',
    tags: ['Cloud 48% Growth', '$240B Backlog', 'Waymo 400K Rides/Wk', '$70B Buyback'],
    risks: { geopolitical: 3, regulatory: 8, competition: 5, valuation: 4, execution: 4 },
    trend: [1000, 1050, 1100, 1080, 1150, 1180, 1196]
  },
  {
    ticker: 'NFLX', name: 'Netflix Inc.', seg: 'US', cat: 'Streaming / Entertainment',
    inv: 698.9, curr: 691.98, ret: -0.96,
    scores: { quality: 7, growth: 7, moat: 8, mgmt: 8, valuation: 5, safety: 7 },
    verdict: 'HOLD', vclass: 'v-hold',
    pe: 39.1, roe: 42.8, cagr5: 13, debt: '0.64x D/E', promoter: 'Reed Hastings 2.6%', mktCap: '$403B',
    news: 'Q4 2025: Revenue $12.05B +18%, 325M subscribers. Warner Bros. acquisition $82.7B announced — largest content deal in history. Ad revenue 2.5x in 2025. FIFA World Cup 2026 exclusive streaming rights in North America.',
    bull: 'Ad revenue doubling YoY. Warner Bros. HBO library. 325M subscribers. FCF machine. FIFA WC 2026.',
    bear: 'Warner Bros. $82.7B raises execution risk. Subscriber growth slowing in mature markets.',
    tags: ['Warner Bros. $82.7B', 'Ad Revenue 2.5x', 'FIFA WC 2026', '325M Subscribers'],
    risks: { geopolitical: 2, regulatory: 4, competition: 7, valuation: 5, execution: 6 },
    trend: [700, 710, 690, 680, 695, 692, 691.9]
  },
  {
    ticker: 'BLK', name: 'BlackRock Inc.', seg: 'US', cat: 'Asset Management',
    inv: 695.56, curr: 642.76, ret: -7.53,
    scores: { quality: 8, growth: 7, moat: 9, mgmt: 8, valuation: 7, safety: 7 },
    verdict: 'BUY ON DIPS', vclass: 'v-buy',
    pe: 22, roe: 10.1, cagr5: 8, debt: '0.4x D/E', promoter: 'Larry Fink 0.6%', mktCap: '$145B',
    news: 'Record $641B net inflows in 2025. GIP acquisition completed — making BlackRock world\'s largest infrastructure investor. HPS Private Credit $12B acquisition closed. AUM $11.5T all-time high.',
    bull: '$11.5T AUM. $641B record inflows. Private markets growing 3x faster than public.',
    bear: 'ROE 10% due to goodwill. ETF fee compression structural. Integration risk GIP/HPS.',
    tags: ['$641B Record Inflows', 'GIP Infra Acquisition', 'HPS Private Credit', '$11.5T AUM'],
    risks: { geopolitical: 3, regulatory: 5, competition: 4, valuation: 4, execution: 5 },
    trend: [700, 680, 660, 670, 650, 645, 642.7]
  },
  {
    ticker: 'TSM', name: 'TSMC', seg: 'US', cat: 'Semiconductor Foundry',
    inv: 580.29, curr: 715.33, ret: 23.28,
    scores: { quality: 9, growth: 9, moat: 10, mgmt: 9, valuation: 7, safety: 6 },
    verdict: 'STRONG BUY', vclass: 'v-strong',
    pe: 28, roe: 31.5, cagr5: 18, debt: '0.25x D/E', promoter: 'Taiwan Gov 6.38%', mktCap: '$1.76T',
    news: 'Q4 2025: Revenue $26.9B +39%. Gross margins 62.3% — record. Arizona Fab 1 first Blackwell wafers produced. 2nm chips ramping H2 2026. EPS growth guidance 53.8% for 2026.',
    bull: 'AI toll road. 2nm lead over rivals. Arizona de-risks Taiwan. EPS +53.8% 2026.',
    bear: 'Taiwan geopolitical risk remains existential. Apple 25% customer concentration.',
    tags: ['Revenue +39% Q4', 'Arizona Fab Live', '2nm Ramp H2 2026', 'EPS +53.8% Guided'],
    risks: { geopolitical: 9, regulatory: 3, competition: 4, valuation: 4, execution: 3 },
    trend: [600, 620, 650, 640, 680, 700, 715.3]
  },
  {
    ticker: 'META', name: 'Meta Platforms', seg: 'US', cat: 'Social Media / AI',
    inv: 501.9, curr: 499.6, ret: -0.42,
    scores: { quality: 9, growth: 8, moat: 9, mgmt: 8, valuation: 8, safety: 7 },
    verdict: 'STRONG BUY', vclass: 'v-strong',
    pe: 26, roe: 37, cagr5: 16, debt: '0.14x D/E', promoter: 'Zuckerberg 13%', mktCap: '$1.56T',
    news: 'Q4 2025: Revenue $59.9B +24%, DAP 3.58B. Q1 2026 guidance $53.5-56.5B — blew past estimates by $2.2B. $115-135B CapEx planned for 2026. Llama 4 released — multimodal, best open-source model. WhatsApp $2B annual run rate.',
    bull: '3.58B DAP. AI ads +3-5% conversion lift. WhatsApp $2B→$20B potential. Fwd PE 21x.',
    bear: '$115-135B CapEx in 2026. Reality Labs $50B cumulative losses. EU regulatory risk.',
    tags: ['DAP 3.58B', 'Q1 Guide Beat $2.2B', 'Llama 4 Released', 'WhatsApp $2B ARR'],
    risks: { geopolitical: 3, regulatory: 8, competition: 5, valuation: 3, execution: 5 },
    trend: [510, 505, 500, 495, 498, 500, 499.6]
  },
  {
    ticker: 'NVDA', name: 'Nvidia Corporation', seg: 'US', cat: 'AI Semiconductors',
    inv: 500.14, curr: 564.73, ret: 12.87,
    scores: { quality: 9, growth: 10, moat: 9, mgmt: 9, valuation: 6, safety: 7 },
    verdict: 'HOLD — CORE', vclass: 'v-hold',
    pe: 44, roe: 118, cagr5: 65, debt: '0.18x D/E', promoter: 'Jensen Huang 3.5%', mktCap: '$4.4T',
    news: 'FY2026: Revenue $215.9B +65%. Q4 $68.1B +73%. Q1 FY27 guide $78B (+7.6% vs estimates). $500B revenue visibility through calendar 2026. Vera Rubin (next-gen) sampling to customers. Jensen: "Blackwell sold out."',
    bull: '$215.9B revenue. CUDA 2M+ devs. Vera Rubin sampling. $500B visibility.',
    bear: '$4.4T market cap requires perfection. Top 4 customers = 61% revenue. China export restrictions.',
    tags: ['$215.9B Revenue FY26', '$500B Visibility', 'Vera Rubin Sampling', 'Blackwell Sold Out'],
    risks: { geopolitical: 6, regulatory: 4, competition: 5, valuation: 5, execution: 3 },
    trend: [500, 510, 530, 520, 550, 560, 564.7]
  },
  {
    ticker: 'MSFT', name: 'Microsoft Corporation', seg: 'US', cat: 'Cloud / AI / Enterprise',
    inv: 450.37, curr: 389.75, ret: -13.44,
    scores: { quality: 9, growth: 8, moat: 9, mgmt: 9, valuation: 8, safety: 9 },
    verdict: 'STRONG BUY', vclass: 'v-strong',
    pe: 24.9, roe: 34.4, cagr5: 16, debt: '0.32x D/E', promoter: 'Insiders 0.6%', mktCap: '$2.9T',
    news: 'Q2 FY26: Revenue $81.3B +17%. Azure +39%. Commercial RPO $625B (+110% YoY — OpenAI\'s $250B Azure commitment). Copilot 15M commercial seats. Stock at 5-year P/E low. $13B+ returned to shareholders.',
    bull: '$625B RPO. Azure capacity-constrained = locked revenue. P/E lowest in 5 years. Copilot 15M→200M.',
    bear: 'Down 13.4% from buy. CapEx $30B/quarter compressing FCF. Copilot slower than expected.',
    tags: ['$625B RPO +110%', 'Azure +39%', 'PE 5-Year Low', 'Copilot 15M Seats'],
    risks: { geopolitical: 2, regulatory: 5, competition: 6, valuation: 3, execution: 4 },
    trend: [450, 430, 410, 420, 400, 395, 389.7]
  },
  {
    ticker: 'IAU', name: 'iShares Gold Trust (ETF)', seg: 'US', cat: 'Commodity ETF',
    inv: 411.61, curr: 484.9, ret: 17.79,
    scores: { quality: 8, growth: 5, moat: 8, mgmt: 8, valuation: 6, safety: 9 },
    verdict: 'HOLD', vclass: 'v-hold',
    pe: 'N/A', roe: 'N/A', cagr5: 'Gold +13%', debt: 'N/A', promoter: 'BlackRock', mktCap: '$30B ETF',
    news: 'Gold hit record $3,100/oz in March 2026 driven by West Asia conflict escalation, central bank buying (3rd year of 1000+ tonne purchases), and Fed rate cut expectations. IAU tracking gold spot with 0.25% expense ratio.',
    bull: 'Central bank buying 1000T+/yr. Rate cuts reduce opportunity cost. West Asia conflict sustained.',
    bear: 'No yield. Underperforms equities in risk-on. Opportunity cost vs dividend stocks.',
    tags: ['Gold $3100/oz Record', 'Central Bank 1000T/yr', '0.25% Expense Ratio', 'West Asia Hedge'],
    risks: { geopolitical: 1, regulatory: 1, competition: 2, valuation: 4, execution: 1 },
    trend: [411, 420, 440, 450, 465, 475, 484.9]
  },
  {
    ticker: 'AAPL', name: 'Apple Inc.', seg: 'US', cat: 'Consumer Tech / Services',
    inv: 402.18, curr: 422.49, ret: 5.09,
    scores: { quality: 9, growth: 6, moat: 9, mgmt: 8, valuation: 6, safety: 8 },
    verdict: 'HOLD', vclass: 'v-hold',
    pe: 35, roe: 150, cagr5: 8, debt: '1.89x D/E', promoter: 'Insiders 0.07%', mktCap: '$3.78T',
    news: 'Q1 FY26: Revenue $143.8B +16% — record. iPhone $85.3B +23%. Services $30B +14%. 2.5B active devices. Apple Intelligence features rolling out. Google AI partnership for Siri next-gen announced.',
    bull: '2.5B devices. Services $120B+ ARR. iPhone record quarter. Google AI Siri partnership.',
    bear: 'PE 35x for 8% revenue CAGR. AI Intelligence behind rivals. China Huawei competition.',
    tags: ['$143.8B Record Quarter', 'Services $30B', 'Google Siri Partnership', '2.5B Active Devices'],
    risks: { geopolitical: 6, regulatory: 6, competition: 5, valuation: 6, execution: 3 },
    trend: [402, 405, 410, 408, 415, 418, 422.4]
  },
  {
    ticker: 'AMD', name: 'Advanced Micro Devices', seg: 'US', cat: 'AI Semiconductors',
    inv: 367.67, curr: 416.38, ret: 13.31,
    scores: { quality: 7, growth: 7, moat: 6, mgmt: 8, valuation: 7, safety: 6 },
    verdict: 'HOLD — WATCH', vclass: 'v-hold',
    pe: 100, roe: 3.5, cagr5: 18, debt: '0.06x D/E', promoter: 'Lisa Su 0.07%', mktCap: '$323B',
    news: 'MI300X revenue exceeded $5B in 2025. Microsoft Azure, Google GCP, Meta deploying MI300X at scale. MI350 series launched Q1 2026. EPYC server CPUs took 34% server market share vs Intel\'s declining 62%.',
    bull: 'MI300X $5B+ revenue. EPYC 34% server share. Fwd PE 22.5x. Hyperscaler diversification.',
    bear: 'Trailing PE 100x. CUDA moat real. ROE 3.5% low. Lisa Su execution risk.',
    tags: ['MI300X $5B Revenue', 'EPYC 34% Server Share', 'MI350 Launched', 'Fwd PE 22.5x'],
    risks: { geopolitical: 4, regulatory: 2, competition: 8, valuation: 5, execution: 6 },
    trend: [367, 380, 400, 390, 410, 415, 416.3]
  },
  {
    ticker: 'WMT', name: 'Walmart Inc.', seg: 'US', cat: 'Retail / E-commerce',
    inv: 305.79, curr: 384.48, ret: 25.75,
    scores: { quality: 7, growth: 6, moat: 8, mgmt: 8, valuation: 5, safety: 7 },
    verdict: 'HOLD', vclass: 'v-hold',
    pe: 38, roe: 22, cagr5: 5, debt: '0.6x D/E', promoter: 'Walton Family 46%', mktCap: '$983B',
    news: 'FY2025: E-commerce grew 22% globally. Walmart Connect ads $4.4B growing 30%+ annually. Walmart+ membership 30M+. Flipkart India GMV growing 24%. Supply chain automation reducing fulfillment cost-per-unit 8%.',
    bull: 'Ads $4.4B growing 30%. Flipkart India 24% GMV growth. E-com +22%. Automation margin tailwind.',
    bear: 'PE 38x expensive for 5% revenue growth. Amazon dominance. Tariff risk on imports.',
    tags: ['E-com +22%', 'Walmart Connect $4.4B', 'Flipkart India +24% GMV', 'Supply Chain Automation'],
    risks: { geopolitical: 3, regulatory: 3, competition: 6, valuation: 7, execution: 4 },
    trend: [305, 320, 340, 350, 365, 375, 384.4]
  },
  {
    ticker: 'XLK', name: 'Technology Sector SPDR ETF', seg: 'US', cat: 'Tech ETF',
    inv: 157.47, curr: 171.27, ret: 8.78,
    scores: { quality: 8, growth: 7, moat: 8, mgmt: 8, valuation: 6, safety: 8 },
    verdict: 'HOLD', vclass: 'v-hold',
    pe: 'N/A', roe: 'N/A', cagr5: '~18% (index)', debt: 'N/A', promoter: 'State Street', mktCap: '$68B ETF',
    news: 'XLK top holdings: AAPL+MSFT form ~40%. Broadcom and Oracle added to top holdings after AI-driven re-weighting. $68B AUM all-time high. Rebalanced quarterly.',
    bull: '0.09% expense ratio. AI secular tailwind. Auto-rebalancing winners. Diversified tech.',
    bear: 'AAPL+MSFT 40% = concentrated. Underperforms in high-dispersion markets.',
    tags: ['0.09% Expense Ratio', '$68B AUM Record', 'AAPL+MSFT+NVDA Top 3', 'AI Secular Tailwind'],
    risks: { geopolitical: 2, regulatory: 3, competition: 3, valuation: 5, execution: 2 },
    trend: [157, 160, 165, 162, 168, 170, 171.2]
  },
  {
    ticker: 'AMZN', name: 'Amazon.com Inc.', seg: 'US', cat: 'Cloud / E-commerce / AI',
    inv: 149.60, curr: 149.80, ret: 0.16,
    scores: { quality: 8, growth: 9, moat: 9, mgmt: 9, valuation: 7, safety: 7 },
    verdict: 'BUY — ADD', vclass: 'v-buy',
    pe: 38, roe: 23.5, cagr5: 12, debt: '0.55x D/E', promoter: 'Jeff Bezos 9.3%', mktCap: '$2.24T',
    news: 'Q4 2025: Revenue $213.4B +14%. AWS $35.6B +24% — fastest in 13 quarters. $244B AWS backlog +40% YoY. Advertising $21.3B +23%. $200B CapEx guided for 2026. Andy Jassy: "We\'ll sell every server, every bit."',
    bull: 'AWS $244B backlog. Ads $21B → $80B+ by 2030. Trainium chips $10B+. Kuiper satellite.',
    bear: '$200B CapEx severely compresses FCF 2026. Q1 guidance wide range. Execution on multiple fronts.',
    tags: ['AWS +24% Fastest in 13Q', '$244B Backlog +40%', 'Ads $21B +23%', '$200B CapEx Year'],
    risks: { geopolitical: 3, regulatory: 7, competition: 6, valuation: 4, execution: 5 },
    trend: [149, 150, 148, 147, 149, 149.5, 149.8]
  },
  // MUTUAL FUNDS
  {
    ticker: 'HDFC GOLD FOF', name: 'HDFC Gold ETF FoF', seg: 'MF', cat: 'Gold Fund',
    inv: 131000, curr: 207000, ret: 57.89,
    scores: { quality: 8, growth: 8, moat: 8, mgmt: 8, valuation: 6, safety: 9 },
    verdict: 'HOLD', vclass: 'v-hold',
    pe: 'N/A', roe: 'N/A', cagr5: 14.2, debt: 'N/A', promoter: 'Expense: 0.15%', mktCap: 'AUM ₹5,200 Cr',
    news: 'Gold hit ₹1.02L/10g in India in March 2026. HDFC Gold FoF directly benefits. Central bank buying (RBI added 12T gold in Feb 2026). West Asia conflict keeping safe-haven demand elevated.',
    bull: 'Gold structural bull run. RBI buying. West Asia conflict. ₹ depreciation adds to INR returns.',
    bear: 'No yield. When geopolitical risk eases, gold corrects. Opportunity cost.',
    tags: ['Gold ₹1.02L/10g', 'RBI Adding Gold', 'Best Performer +57.89%', 'Geopolitical Hedge'],
    risks: { geopolitical: 1, regulatory: 1, competition: 1, valuation: 4, execution: 1 },
    trend: [131, 145, 160, 175, 190, 200, 207]
  },
  {
    ticker: 'ICICI MULTI ASSET', name: 'ICICI Pru Multi Asset Fund', seg: 'MF', cat: 'Hybrid Fund',
    inv: 50000, curr: 56810, ret: 13.63,
    scores: { quality: 8, growth: 7, moat: 7, mgmt: 9, valuation: 7, safety: 8 },
    verdict: 'HOLD — CORE', vclass: 'v-hold',
    pe: 'N/A', roe: 'N/A', cagr5: 22.3, debt: 'N/A', promoter: 'Expense: 0.84%', mktCap: 'AUM ₹52,000 Cr',
    news: '5Y CAGR 22.3% — top decile in hybrid category. Gold allocation 15% boosted returns in 2025-26. Fund automatically rotates between equity, gold and debt based on valuation signals. PlumbLine endorsed.',
    bull: '22.3% 5Y CAGR. Auto-allocation. Gold 15% in current environment is perfect. PlumbLine rated.',
    bear: '0.84% expense ratio slightly higher than index funds. Returns depend on allocation model accuracy.',
    tags: ['5Y CAGR 22.3%', 'Gold 15% Allocation', 'PlumbLine Endorsed', 'Auto-Rebalancing'],
    risks: { geopolitical: 2, regulatory: 2, competition: 3, valuation: 3, execution: 3 },
    trend: [50, 52, 54, 53, 55, 56, 56.8]
  },
  {
    ticker: 'PPFAS', name: 'Parag Parikh Flexi Cap', seg: 'MF', cat: 'Equity - Flexi Cap',
    inv: 50000, curr: 51020, ret: 2.04,
    scores: { quality: 9, growth: 7, moat: 7, mgmt: 9, valuation: 7, safety: 8 },
    verdict: 'HOLD — CORE', vclass: 'v-hold',
    pe: 'N/A', roe: 'N/A', cagr5: 19.87, debt: 'N/A', promoter: 'Expense: 0.63%', mktCap: 'AUM ₹1.33L Cr',
    news: 'Recent underperformance due to US tech holdings (Google, Meta). Rajeev Thakkar maintained contrarian stance — did not sell US tech. Fund holds SEBI-approved 10% global allocation in Alphabet, Meta. 10Y CAGR 19.24%.',
    bull: '10Y CAGR 19.24%. Value approach. Global diversification. Morningstar Silver rated.',
    bear: '2.04% return — US tech drag. 1Y underperformance vs category. Low AUM growth risk.',
    tags: ['10Y CAGR 19.24%', 'Morningstar Silver', 'US Tech Holdings', 'Value+Growth Blend'],
    risks: { geopolitical: 3, regulatory: 2, competition: 3, valuation: 4, execution: 3 },
    trend: [50, 51, 50.5, 50.8, 50.2, 50.5, 51]
  },
  {
    ticker: 'DSP NEXT50', name: 'DSP Nifty Next 50 Index', seg: 'MF', cat: 'Index Fund',
    inv: 49600, curr: 48790, ret: -1.63,
    scores: { quality: 7, growth: 7, moat: 7, mgmt: 7, valuation: 7, safety: 7 },
    verdict: 'HOLD', vclass: 'v-hold',
    pe: 'N/A', roe: 'N/A', cagr5: 15.2, debt: 'N/A', promoter: 'Expense: 0.30%', mktCap: 'AUM ₹3,400 Cr',
    news: 'Nifty Next 50 contains future large-caps. Recent underperformance due to mid-large cap FII selling. Long-term 5Y CAGR 15.2%. Passive fund — no manager risk. Suitable as core holding.',
    bull: 'Low cost 0.30%. Future large caps. 15.2% 5Y CAGR. No manager risk.',
    bear: '-1.63% currently. Mid-large cap selling by FIIs hurts this index.',
    tags: ['Future Large Caps', '0.30% Cost', 'Passive Core', '5Y CAGR 15.2%'],
    risks: { geopolitical: 3, regulatory: 2, competition: 2, valuation: 4, execution: 1 },
    trend: [49.6, 49.2, 48.8, 49, 48.5, 48.6, 48.7]
  },
  {
    ticker: 'ICICI QUALITY30', name: 'ICICI Pru Nifty200 Quality 30', seg: 'MF', cat: 'Index Fund',
    inv: 50000, curr: 46590, ret: -6.81,
    scores: { quality: 7, growth: 6, moat: 7, mgmt: 7, valuation: 6, safety: 7 },
    verdict: 'HOLD', vclass: 'v-hold',
    pe: 'N/A', roe: 'N/A', cagr5: 14.8, debt: 'N/A', promoter: 'Expense: 0.29%', mktCap: 'AUM ₹2,800 Cr',
    news: 'Quality factor underperforming in 2025-26 as market rotated to value and cyclicals. Factor rotation is temporary. In past cycles (2020-21 correction), quality outperformed in the recovery. Low cost 0.29%.',
    bull: 'Quality factor recovers in downturns. 0.29% cost. 14.8% 5Y CAGR.',
    bear: '-6.81% currently. Factor rotation away from quality. Overlap with other large cap funds.',
    tags: ['Quality Factor', 'Nifty 200 Universe', '0.29% Cost', 'Rotation Headwind'],
    risks: { geopolitical: 2, regulatory: 2, competition: 3, valuation: 4, execution: 2 },
    trend: [50, 49, 48, 47.5, 47, 46.8, 46.5]
  },
  {
    ticker: 'AXIS SMALL', name: 'Axis Small Cap Fund', seg: 'MF', cat: 'Equity - Small Cap',
    inv: 35000, curr: 32660, ret: -6.68,
    scores: { quality: 7, growth: 8, moat: 6, mgmt: 7, valuation: 7, safety: 5 },
    verdict: 'HOLD', vclass: 'v-hold',
    pe: 'N/A', roe: 'N/A', cagr5: 25.8, debt: 'N/A', promoter: 'Expense: 0.52%', mktCap: 'AUM ₹23,000 Cr',
    news: 'Small cap category corrected 15-20% from peaks. Axis Small Cap selective quality-focused approach insulates somewhat. 5Y CAGR 25.8% — one of the better small cap track records. Small cap bear markets typically last 12-18 months.',
    bull: '5Y CAGR 25.8%. Quality-focused selection. Small cap corrections are best SIP times.',
    bear: '-6.68% currently. Small cap category in bear phase. 12-18 months to recovery typically.',
    tags: ['5Y CAGR 25.8%', 'Quality Small Cap', 'Bear Phase — Stay Invested', 'Best SIP Opportunity'],
    risks: { geopolitical: 3, regulatory: 2, competition: 4, valuation: 4, execution: 4 },
    trend: [35, 34, 33, 33.5, 32.8, 32.7, 32.6]
  },
  {
    ticker: 'SBI ELSS', name: 'SBI ELSS Tax Saver', seg: 'MF', cat: 'ELSS Fund',
    inv: 25000, curr: 25040, ret: 0.18,
    scores: { quality: 8, growth: 7, moat: 7, mgmt: 8, valuation: 7, safety: 7 },
    verdict: 'HOLD — BEST ELSS', vclass: 'v-hold',
    pe: 'N/A', roe: 'N/A', cagr5: 19.58, debt: 'N/A', promoter: 'Expense: 0.89%', mktCap: 'AUM ₹28,000 Cr',
    news: 'Ranked #2 out of 23 ELSS funds by INDmoney. 3Y CAGR 24.38% outstanding. Banking and financials heavy portfolio benefiting from credit cycle. Q4 2025 added positions in PSU banks during dip.',
    bull: '#2 Ranked ELSS. 5Y CAGR 19.58%. 3Y CAGR 24.38%. Banking sector plays well.',
    bear: '0.89% relatively high for an ELSS. Banking heavy = concentration risk.',
    tags: ['#2 Ranked ELSS', '3Y CAGR 24.38%', 'Banking+Financials Heavy', 'Best ELSS to Consolidate Into'],
    risks: { geopolitical: 2, regulatory: 3, competition: 3, valuation: 4, execution: 3 },
    trend: [25, 25.2, 24.8, 25, 25.1, 24.9, 25]
  },
  {
    ticker: 'MOTILAL MIDCAP', name: 'Motilal Oswal Midcap Fund', seg: 'MF', cat: 'Equity - Midcap',
    inv: 25000, curr: 20100, ret: -19.60,
    scores: { quality: 4, growth: 5, moat: 4, mgmt: 4, valuation: 4, safety: 4 },
    verdict: 'REVIEW — SWITCH', vclass: 'v-reduce',
    pe: 'N/A', roe: 'N/A', cagr5: 22.45, debt: 'N/A', promoter: 'Expense: 0.77%', mktCap: 'AUM ₹28,000 Cr',
    news: 'Portfolio PE 46.63x vs category average 34.33x — dangerously concentrated in expensive stocks. Alpha -47.17 and Sharpe ratio -0.59. Benchmark Nifty Midcap 150 beat this fund over 1Y and 3Y. 5Y CAGR carried by 2021-23 bull run.',
    bull: '5Y CAGR 22.45% historical. Fund manager Niket Shah still credible.',
    bear: '-19.6% your loss. PE 46.63x excessive. Alpha -47. Negative Sharpe. Underperforms benchmark.',
    tags: ['WORST FUND -19.6%', 'PE 46.63x vs 34.33 Avg', 'Alpha -47', 'Negative Sharpe -0.59'],
    risks: { geopolitical: 3, regulatory: 2, competition: 5, valuation: 8, execution: 8 },
    trend: [25, 24, 23, 22, 21, 20.5, 20.1]
  },
  {
    ticker: 'HDFC MIDCAP', name: 'HDFC Mid Cap Opportunities', seg: 'MF', cat: 'Equity - Midcap',
    inv: 22900, curr: 23240, ret: 1.48,
    scores: { quality: 8, growth: 8, moat: 7, mgmt: 9, valuation: 7, safety: 7 },
    verdict: 'BUY — ADD SIP', vclass: 'v-buy',
    pe: 'N/A', roe: 'N/A', cagr5: 22.7, debt: 'N/A', promoter: 'Expense: 0.72%', mktCap: 'AUM ₹80,000 Cr',
    news: 'HDFC Midcap consistently top-quartile since inception. Fund manager Chirag Setalvad has 18 years tenure. Q4 2025 navigated midcap correction better than peers. 5Y CAGR 22.7% with lower volatility than peers.',
    bull: '5Y CAGR 22.7%. Top-quartile consistency. 18-year manager tenure. Lower volatility than peers.',
    bear: 'Large AUM ₹80,000 Cr limits ability to invest in very small mid caps. 0.72% cost.',
    tags: ['5Y CAGR 22.7%', 'Chirag Setalvad 18Y Tenure', 'Top Quartile Consistency', 'Add SIP Recommended'],
    risks: { geopolitical: 2, regulatory: 2, competition: 3, valuation: 4, execution: 2 },
    trend: [22.9, 23, 23.1, 23, 23.2, 23.3, 23.2]
  },
  {
    ticker: 'KOTAK SMALL', name: 'Kotak Small Cap Fund', seg: 'MF', cat: 'Equity - Small Cap',
    inv: 22000, curr: 19180, ret: -12.82,
    scores: { quality: 7, growth: 7, moat: 6, mgmt: 7, valuation: 7, safety: 5 },
    verdict: 'HOLD — TOP UP', vclass: 'v-hold',
    pe: 'N/A', roe: 'N/A', cagr5: 24.1, debt: 'N/A', promoter: 'Expense: 0.46%', mktCap: 'AUM ₹17,000 Cr',
    news: 'Small cap category correction. Kotak Small Cap has outperformed benchmark in every 3-year rolling period. 5Y CAGR 24.1% with low 0.46% expense ratio. Current dip is category-wide, not fund-specific.',
    bull: '5Y CAGR 24.1%. Low 0.46% expense. Outperforms benchmark consistently. Top up opportunity.',
    bear: '-12.82% currently. Small cap bear phase. 12-18 months patience required.',
    tags: ['5Y CAGR 24.1%', '0.46% Low Cost', 'Category Correction', 'Best Top-Up Opportunity'],
    risks: { geopolitical: 3, regulatory: 2, competition: 4, valuation: 4, execution: 4 },
    trend: [22, 21, 20, 20.5, 19.8, 19.5, 19.1]
  },
  {
    ticker: 'SBI CONTRA', name: 'SBI Contra Fund', seg: 'MF', cat: 'Equity - Contra',
    inv: 20000, curr: 19580, ret: -2.08,
    scores: { quality: 8, growth: 8, moat: 7, mgmt: 8, valuation: 8, safety: 7 },
    verdict: 'HOLD', vclass: 'v-hold',
    pe: 'N/A', roe: 'N/A', cagr5: 28.5, debt: 'N/A', promoter: 'Expense: 0.95%', mktCap: 'AUM ₹32,000 Cr',
    news: 'SBI Contra\'s 5Y CAGR of 28.5% is top-decile across ALL equity fund categories. Fund currently positioned in out-of-favour IT and pharma sectors — expecting H2 2026 recovery. Contrarian bet on rural India and PSU capex playing out slowly.',
    bull: '5Y CAGR 28.5% — top decile. Contra approach adds differentiation. Currently positioning for IT+pharma recovery.',
    bear: '-2.08% short term. 0.95% expense ratio. Contra strategy requires 3-5 year patience.',
    tags: ['5Y CAGR 28.5% Top Decile', 'Contrarian IT+Pharma Bet', 'Rural India Play', 'H2 2026 Recovery Bet'],
    risks: { geopolitical: 2, regulatory: 2, competition: 3, valuation: 3, execution: 4 },
    trend: [20, 20.2, 19.8, 20, 19.7, 19.6, 19.5]
  },
  {
    ticker: 'AXIS LARGE CAP', name: 'Axis Large Cap Fund', seg: 'MF', cat: 'Equity - Large Cap',
    inv: 10040, curr: 9780, ret: -2.61,
    scores: { quality: 3, growth: 3, moat: 4, mgmt: 3, valuation: 4, safety: 5 },
    verdict: 'EXIT', vclass: 'v-exit',
    pe: 'N/A', roe: 'N/A', cagr5: 11.2, debt: 'N/A', promoter: 'Expense: 1.54%', mktCap: 'AUM ₹20,000 Cr',
    news: '5Y CAGR 11.2% — worst large cap fund in your portfolio, 3-4% below category average. Axis AMC front-running scandal (2022) permanently impacted fund\'s edge. 1.54% expense ratio is the highest in your MF portfolio. Redeploy to DSP Nifty Next 50 or Nippon Midcap 150 Index.',
    bull: 'Nothing compelling. Maybe a new management team could turnaround.',
    bear: '5Y CAGR 11.2% = 3-4% below peers. 1.54% = highest cost. Post-scandal underperformance structural.',
    tags: ['5Y CAGR 11.2% — WORST', '1.54% HIGHEST COST', 'Post-Scandal Underperformance', 'EXIT NOW'],
    risks: { geopolitical: 2, regulatory: 3, competition: 3, valuation: 6, execution: 9 },
    trend: [10.5, 10.2, 10, 9.9, 9.8, 9.7, 9.7]
  },
];

export const USD_INR = 92.56;

export const getStats = () => {
  const inInv = allAssets.filter(a => a.seg === 'IN').reduce((s, a) => s + a.inv, 0);
  const inCurr = allAssets.filter(a => a.seg === 'IN').reduce((s, a) => s + a.curr, 0);
  const usInv = allAssets.filter(a => a.seg === 'US').reduce((s, a) => s + a.inv, 0);
  const usCurr = allAssets.filter(a => a.seg === 'US').reduce((s, a) => s + a.curr, 0);
  const mfInv = allAssets.filter(a => a.seg === 'MF').reduce((s, a) => s + a.inv, 0);
  const mfCurr = allAssets.filter(a => a.seg === 'MF').reduce((s, a) => s + a.curr, 0);

  const usInvINR = usInv * USD_INR;
  const usCurrINR = usCurr * USD_INR;

  const totalInv = inInv + usInvINR + mfInv;
  const totalCurr = inCurr + usCurrINR + mfCurr;
  const totalPL = totalCurr - totalInv;
  const totalRet = (totalPL / totalInv) * 100;

  return {
    inInv, inCurr,
    usInv, usCurr,
    mfInv, mfCurr,
    totalInv, totalCurr, totalPL, totalRet
  };
};
